version: "3"
services:
  nginx:
    image: nginx:1.15.7-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html/:rw
      - ./conf/conf.d:/etc/nginx/conf.d/:rw
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx:/var/log/nginx/:rw
    environment:
      TZ: "Asia/Shanghai"
    restart: always
    networks:
      - default

  php72:
    image: dnmp_php72:1.0
    container_name: php72
    volumes:
      - ./www:/var/www/html/:rw
      - ./conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php:/var/log/php
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    networks:
      - default
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - TZ=Asia/Shanghai

  mysql:
    image: mysql:8.0.13
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      TZ: "Asia/Shanghai"

networks:
  default:
